// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM3IZDLqLY3FdWf-j33uzAzMO8P9BaOmg',
    appId: '1:308621725070:web:8894104821c0a3458ba8df',
    messagingSenderId: '308621725070',
    projectId: 'baja-sun-city',
    authDomain: 'baja-sun-city.firebaseapp.com',
    storageBucket: 'baja-sun-city.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-ZNJLPLVrh3YywFkoTBV5AaxCbsnxMEQ',
    appId: '1:308621725070:android:e4d145fa7ebb9ce88ba8df',
    messagingSenderId: '308621725070',
    projectId: 'baja-sun-city',
    storageBucket: 'baja-sun-city.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOOiCk2GvR9wizmzM_WUP4tEVwLenGnaA',
    appId: '1:308621725070:ios:01d2dc64d17275198ba8df',
    messagingSenderId: '308621725070',
    projectId: 'baja-sun-city',
    storageBucket: 'baja-sun-city.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM3IZDLqLY3FdWf-j33uzAzMO8P9BaOmg',
    appId: '1:308621725070:web:8ae2d46541528a098ba8df',
    messagingSenderId: '308621725070',
    projectId: 'baja-sun-city',
    authDomain: 'baja-sun-city.firebaseapp.com',
    storageBucket: 'baja-sun-city.firebasestorage.app',
  );
}
